### ISSUE TITLE
Fabric 1.19.3 crash: java.lang.NoSuchFieldError: field_11142

### ISSUE THREAD

**Issue by lospejos** [spoorn/SpoornBountyMobs#13]
IDK is it a this mod's bug or other mod's bug.

Fabric version: `fabric-api-0.69.1+1.19.3`
Spoorn Bounty Mobs version: `spoornbountymobs-3.0.1-1.19.2`

Error:

```
java.lang.NoSuchFieldError: field_11142
	at org.spoorn.spoornbountymobs.entity.SpoornBountyEntityRegistry.lambda$registerServerStartedCallback$2(SpoornBountyEntityRegistry.java:130)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49)
	at net.minecraft.server.MinecraftServer.handler$bfm000$afterSetupServer(MinecraftServer.java:4824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:655)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

Please assist.

Thanks!

**Comment by spoorn** [comment]
only available up to 1.19.2 for 1.19 versions
